![imagen](./img/ejercicios.png)

## Ejercicio 1
*(Exercise 1)*

1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
   *(Create an array from 0 to 9 called `my_array`)*
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.
   *(Print the elements [9 7 5 3 1] in that order.)*

## Ejercicio 2
*(Exercise 2)*

Imprime por pantalla la secuencia [8 7] del array `my_array`
*(Print the sequence [8 7] from the array `my_array`)*

## Ejercicio 3
*(Exercise 3)*

Imprime por pantalla la secuencia [2 1 0] de `my_array`
*(Print the sequence [2 1 0] from `my_array`)*

## Ejercicio 4
*(Exercise 4)*

1. Crea una matriz de 4x5, con una secuencia del 1 al 20
   *(Create a 4x5 matrix with a sequence from 1 to 20)*
2. Invierte totalmente la matriz. Tanto las filas, como las columnas
   *(Fully invert the matrix. Both rows and columns)*

## Ejercicio 5
*(Exercise 5)*

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
*(Get the following array, starting from the matrix in exercise 4)*

```Python
array([[1, 2],
       [6, 7]])
```

## Ejercicio 6
*(Exercise 6)*

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
*(Get the following array, starting from the matrix in exercise 4)*

```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

## Ejercicio 7
*(Exercise 7)*

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
*(Get the following array, starting from the matrix in exercise 4)*

```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

## Ejercicio 8
*(Exercise 8)*

Dado el siguiente array:
*(Given the following array:)*

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.
*(Filter the array to keep only the parrots.)*

Resuélvelo de dos maneras diferentes
*(Solve it in two different ways)*

## Ejercicio 9
*(Exercise 9)*

Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2
*(Create a sequence of 20 elements and transform it into an array composed of 2 matrices of 5x2)*

## Ejercicio 10
*(Exercise 10)*

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
*(Get the following array, starting from the matrix in exercise 4)*

```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

## Ejercicio 11
*(Exercise 11)*

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?
*(Create an array of 10 zeros. How much memory does it take?)*

Sustituye el 4to elemento por 1, e imprime el array por pantalla
*(Replace the 4th element with 1, and print the array)*

## Ejercicio 12
*(Exercise 12)*

Crea un vector que vaya del 10 al 49
*(Create a vector from 10 to 49)*

Inviértelo
*(Invert it)*

## Ejericio 13
*(Exercise 13)*

Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)
*(Find the indices of the non-zero values of the following vector [1,2,0,0,4,0]. The output would be [0, 1, 4]. [Find the appropriate method in the documentation.](https://numpy.org/doc/))*

## Ejercicio 14
*(Exercise 14)*

Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.
*(Create a 10x10 matrix of random numbers. Find the minimum and maximum values.)*

## Ejercicio 15
*(Exercise 15)*

Crea un vector aleatorio de tamaño 30 y calcula su media
*(Create a random vector of size 30 and calculate its mean)*

## Ejercicio 16
*(Exercise 16)*

Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s
*(Create a 2D square array, with whatever dimensions you want, but with all the border composed of 1s, and the interior of 0s)*

## Ejercicio 17
*(Exercise 17)*

Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
*(Create an 8x8 matrix and fill it with 0s and 1s. You have to replicate:)*

```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

## Ejercicio 18
*(Exercise 18)*

Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)
*(Replicate the matrix from the previous section, but this time using [the `tile` function](https://numpy.org/doc/stable/reference/generated/numpy.tile.html))*

## Ejercicio 9
*(Exercise 9)*

Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).
*(Create a random 5x5 matrix and standardise its values. To normalise you have to subtract the mean (`np.mean`) and divide the result by the standard deviation (`np.std`).)*

## Ejercicio 10
*(Exercise 10)*

1. Crea una secuencia de números que vayan del 0 al 10.
   *(Create a sequence of numbers from 0 to 10.)*
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
   *(Create a new array, starting from the previous one, but replacing all elements between 3 and 8 with the value -1)*
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8
   *(Create a new array that negates all elements between 3 and 8)*

## Ejercicio 11
*(Exercise 11)*

#### Bonus track. Mini hundir la flota
*(Bonus track. Mini Battleship)*

1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
   *(Create a 10x10 board filled with the space character ( ).)*
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas.
   *(Position a pair of ships at [(0,1), (1,1)] and [(1,3), (1,4), (1,5), (1,6)]. Ships will be uppercase Os.)*
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
   *(Receive a shot on one of the ships, replacing the O with an X)*
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
   *(Receive a shot in water, replacing one of the spaces with a dash: -)*
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**
   *(Ignoring the shots received, now try to position another 4-position ship on the board, but **RANDOMLY.)**

**Consejo apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).
*(**Tip for part 5**: The ship will have a random initial position on the board, and a random orientation too (N,S,E,W).)*

Usa `import random` para elegir las coordenadas aleatorias.
*(Use `import random` to choose the random coordinates.)*

array([['-', 'X', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')