In [1]:
import numpy as np

# el if va con estos --> not or and  if True
# las máscaras booleanas van con estos --> ~   |   &  

# not, and, or --> son operadores para booleanos True, False
# ~, &, | --> son operadores booleanos a nivel de bit 0010 & 1101 --> 0000



In [18]:
m = 5
n = 2

if m ==5 and n <= 2 or n < 10: # if True and True
    print("hola")

hola


In [20]:
np_array1 = np.arange(10)
np_array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
condicion1 = np_array1 >= 2
condicion2 =  np_array1 < 7
condicion_total = condicion1 & condicion2

np_array1[condicion_total]

array([2, 3, 4, 5, 6])

In [35]:
if True:
    print("hola")
if 0:
    print("hola2")
if [0]:
    print("hola3")

if np_array1.all():
    print("hola4")

hola
hola3


In [39]:
if None:
    print("holita")

In [ ]:
# if una_funcion():

False

In [ ]:
n = 4 # 0001010101
print(~n)

-5


In [ ]:
# bool
# con int, si me das cero, doy False, si no es cero, doy True
# con listas, si es lista vacía, doy False, si tiene elementos, doy True
#

In [16]:
bool([])
bool([1,2,3,4])

True

In [13]:
bool(0)

False

In [5]:
if m ==5 & n <= 2:
    print("hola")

In [7]:
False & True

False

In [72]:
mensaje= "hola\nadiós"


In [73]:
mensaje

'hola\nadiós'

In [74]:
print(mensaje)

hola
adiós


In [ ]:
np_array2 = np_array1.reshape(10)
print(np_array2[9] * 2) # 18
print(np_array2[9:] * 2)

18
[18]


In [71]:
np.array([1,2,3]) * 2

array([2, 4, 6])

In [ ]:
a1 = np_array2.reshape(2,5,1)

# concatenar en el eje 1
# siempre necesito que el segundo array tenga las mismas dimensiones
# excepto en este caso, el eje 1

# (2,x,1)   (2,3,1)
a1

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [87]:
a2 = np.arange(6).reshape(2,3,1)
a2

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [90]:
np.concatenate([a1, a2], axis=1).shape

(2, 8, 1)

In [91]:
np.concatenate([a1, a2], axis=1)

array([[[0],
        [1],
        [2],
        [3],
        [4],
        [0],
        [1],
        [2]],

       [[5],
        [6],
        [7],
        [8],
        [9],
        [3],
        [4],
        [5]]])

In [152]:
a7 = np.arange(24).reshape(2,3,4)
a7

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [153]:
# axis = 2  (2,3,2)
a8 = np.arange(12).reshape(2,3,2)
a8

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [155]:
np.concatenate([a7, a8], axis = 2).shape

(2, 3, 6)

In [ ]:
# (2,5,12,4)
# axis = 0
# (6,5,12,4)
# (8,5,12,4)

In [100]:
def mi_funcion(a,b,c,d = 10, *args, **kwargs):
    print("a -->", a)
    print("b -->", b)
    print("c -->", c)
    print("d -->", d)
    print("args -->", args)
    print("kwargs -->", kwargs)
    
def otra_funcion(a,b,/,c,d, *, e=10, f=20):
    print("a", a)
    print("b", b)
    print("c", c)
    print("d", d)
    print("e", e)
    print("f", f)
    
otra_funcion(1,2,c=3,d=4, f=100)

a 1
b 2
c 3
d 4
e 10
f 100


In [101]:
# vstack

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np_array2 # (10,)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
np_array2[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
#
np_array2.reshape(2,5)#[:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [129]:
a5 = np.arange(30).reshape(3,10)
a5

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [143]:
a5[-1:]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
# [   [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]   ]
#      0   1   2   3
#     [20,20,20,23]
#     23

In [149]:
a5[-1:,[0,0,0,3]]

array([[20, 20, 20, 23]])

In [150]:
a5[-1:,3]

array([23])

In [168]:
def funcion2(a, b=None, c=None, /,*,d=10): # positional only / * keyword only
    print("a", a)
    print("b", b)
    print("c", c)
    print("d", d)
    
funcion2(1, 20, 30, d=40)
    

a 1
b 20
c 30
d 40
